[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
no_match_test = "test_Custom"
solc = '0.8.13'

fs_permissions = [{ access = "read", path = "./" }]

[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}", chain = 43113 }
avalanche = { key = "${SNOWTRACE_API_KEY}", chain = 43114 }
bnb_smart_chain_testnet = { key = "${BSCSCAN_API_KEY}", chain = 97 }
bnb_smart_chain = { key = "${BSCSCAN_API_KEY}", chain = 56 }

# To test the SVG generation, use "export FOUNDRY_PROFILE=svgtesting"
[profile.svgtesting]
match_test = "test_Custom_SVGGeneration"
no_match_test = "Foo"
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
gas_limit = "18446744073709551615"

[profile.upgradetesting]
match_test = "test_Custom_UpgradeDescriptor"
no_match_test = "Foo"
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
# memory_limit = 100_000_000_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
